openapi: 3.0.0
info:
  title: 1DV027 API
  description: "An api for the course 1dv027, view anime data and be notified about new episodes"
  version: 0.0.0
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
tags:
  - name: auth
    description: Everything about your Pets
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /login:
    post:
      tags: 
      - auth
      summary: Allows the user to login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string
      responses:
        '200':
          description: 'Successful login'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  accesstoken:
                    type: string
                    example:
                      eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZ0BncmFuZGluLmdtYWlsLmNvbSI6InBnQGdyYW5kaW4uZ21haWwuY29tIiwiaWF0IjoxNzEwMzM4Nzc1LCJleHAiOjE3MTAzNDc0MTV9.OpvRoQYfCK1RDYnCrI50sAx3kpJz74p1uKjD_EuuTeFJdU_O65JkrUNWQej35CHsbNQ6l7yC79UK_Avm_5o3aCsMPk9IXb1zqsLq3yi4BEWLjLXuFJB_fAvsur9mFGvGPZkNc3JXFxLdKbU4zVK1Ca11TXq3igET1-S8E7zckKdE17KHNQRzRXGHfD9_G0Ct57vfF_nDcGnAhGFsLqcVrGtLV5gecXI8ryNfVLeKwzmgdSQ-Ok8UcvWCOEvxkaQd-2IxcE7Ablf9sBtVdeLADcfKX0qLwjFzD8UbA8F-DXXmIejjVmMx_aawiVBEZqe03ZpaVgz3i8nC3MXZVyrwfw
                  refreshtoken:
                    type: string
                    example:
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQYXNoYSI6IlBhc2hhIiwiaWF0IjoxNzEwMzM4Nzc1LCJleHAiOjE3MTAzOTkyNTV9.MuwJKRVMFtnsb321CZDeQsiR2Pb2meDRcnro6Sp6mNo
      
        '401':
          description: 'Invalid credentials'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example:
                      401
                  message:
                    type: string
                    example: 
                      The credentials provided are invalid
        '500':
          description: An unexpected condition was encountered on the server.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: number
                    example:
                      500
                  message:
                    type: string
                    example:
                      An unexpected condition was encountered on the server
  /register:
    post:
      tags:
      - auth
      summary: 'The user calls this to register an account with the API.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: 'Successful registration, a new account is created.'
          content:
           application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example:
                      201
                  id:
                    type: string
                    example:
                      65f19170a691b9af5c9ba094
        '409':
          description: 'Data provided by the client is duplicate of what is present on server.'
          content:
           application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example:
                     409
                  message:
                    type: string
                    example: 
                      Duplicate data found, this data already exists

        '400':
          description: 'Something went wrong with the request due to what was perceived to be a client error'
          content:
           application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example:
                      400 
                  message:
                    type: string
                    example: 
                      'Invalid data provided'
        '500':
          description: An unexpected condition was encountered on the server.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: number
                    example:
                      500
                  message:
                    type: string
                    example:
                      An unexpected condition was encountered on the server
  /refresh:
    post:        
      security:
        - bearerAuth: []
      tags:
        - auth
      summary: Issues a renewed access if the refresh token is valid.
      responses:
        '500':
          description: An unexpected condition was encountered on the server.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: number
                    example:
                      500
                  message:
                    type: string
                    example:
                      An unexpected condition was encountered on the server
        '401':
          description: The token given is either expried, invalid or the authentication scheme is incorrect.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: number
                    example:
                      401
                  message:
                    type: string
                    example:
                      Invalid authentication scheme


